# ETL

In [1]:
import pandas as pd
import unicodedata

Ruta Bases de Datos

In [2]:
ruta_base = r"C:\Users\USUARIO\OneDrive - NEUROMEDICA S.A.S\Escritorio\PROYECTO_ANALISIS_DE_DATOS"
ruta_archivo_distribucion_cartera = r"\Bases_datos\Distribución_de_cartera_por_producto_20260423.xlsx"
ruta_archivo_saldo_captaciones = r"Bases_datos\Saldo_de_las_captaciones_y_colocaciones_por_municipios_20260429.xlsx"

data_saldo_captaciones = pd.read_excel(f"{ruta_base}\{ruta_archivo_saldo_captaciones}")
data_distribucion_cartera = pd.read_excel(f"{ruta_base}\{ruta_archivo_distribucion_cartera}")

<string>:5: SyntaxWarning: invalid escape sequence '\{'
<string>:6: SyntaxWarning: invalid escape sequence '\{'
<>:5: SyntaxWarning: invalid escape sequence '\{'
<>:6: SyntaxWarning: invalid escape sequence '\{'
<string>:5: SyntaxWarning: invalid escape sequence '\{'
<string>:6: SyntaxWarning: invalid escape sequence '\{'
<>:5: SyntaxWarning: invalid escape sequence '\{'
<>:6: SyntaxWarning: invalid escape sequence '\{'
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_24164\4111864755.py:5: SyntaxWarning: invalid escape sequence '\{'
  data_saldo_captaciones = pd.read_excel(f"{ruta_base}\{ruta_archivo_saldo_captaciones}")
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_24164\4111864755.py:6: SyntaxWarning: invalid escape sequence '\{'
  data_distribucion_cartera = pd.read_excel(f"{ruta_base}\{ruta_archivo_distribucion_cartera}")

In [3]:
#Aplanar columnas
def aplanar_columnas(columnas):
    new_cols = []
    for col in columnas:
        if isinstance(col,tuple):
            col = [str(c).lower().strip().replace(" ", "_") for c in col
                   if c
                   and
                   "unname" not in str(c).lower()]
            new_cols.append(col[-1])
        else:
            new_cols.append(str(col).lower().strip().replace(" ", "_"))
    return new_cols

In [4]:
data_saldo_captaciones.columns = aplanar_columnas(columnas=data_saldo_captaciones.columns)
data_distribucion_cartera.columns = aplanar_columnas(columnas=data_distribucion_cartera.columns)

In [5]:
data_saldo_captaciones.columns

Index(['tipo_de_entidad', 'código_de_entidad', 'código_del_departamento',
       'código_del_municipio', 'nombre_del_municipio', 'fecha_de_corte',
       'depósitos_en_cuenta_corriente_bancaria', 'depósitos_simples',
       'certificados_de_depósito_a_término', 'depósitos_de_ahorro',
       'cuenta_de_ahorros_de_valor_real', 'cuentas_de_ahorro_especial',
       'certificado_de_ahorro_valor_real', 'documentos_por_pagar',
       'cuenta_centralizada', 'títulos_de_inversión_en_circulación',
       'cartera_de_créditos', 'créditos_de_vivienda',
       'categoría_a_riesgo_normal', 'categoría_b_riesgo_aceptable',
       'categoría_c_riesgo_apreciable', 'categoría_d_riesgo_significativo',
       'categoría_e_riesgo_de_incobrabilidad',
       'categoría_a_riesgo_normal,_garantía_idónea,_créditos_y_leasing_de_consumo',
       'categoría_b_riesgo_aceptable,_garantía_idónea,_créditos_y_leasing_de_consumo',
       'categoría_c_riesgo_apreciable,_garantía_idónea,_créditos_y_leasing_de_consumo',
       'categoría_d_riesgo_significativo,_garantía_idónea,_créditos_y_leasing_de_consumo',
       'categoría_e_riesgo_de_incobrabilidad,_garantía_idónea,_créditos_y_leasing_de_consumo',
       'categoría_a_riesgo_normal,_otras_garantías,_créditos_y_leasing_de_consumo',
       'categoría_b_riesgo_aceptable,_otras_garantías,_créditos_y_leasing_de_consumo',
       'categoría_c_riesgo_apreciable,_otras_garantías,_créditos_y_leasing_de_consumo',
       'categoría_d_riesgo_significativo,_otras_garantías,_créditos_y_leasing_de_consumo',
       'categoría_e_riesgo_de_incobrabilidad,_otras_garantías,_créditos_y_leasing_de_consumo',
       'microcréditos,_garantía_idónea', 'categoría_a_riesgo_normal_c29',
       'categoría_b_riesgo_aceptable_c30', 'categoría_c_riesgo_apreciable_c31',
       'categoría_d_riesgo_significativo_c32',
       'categoría_e_riesgo_de_incobrabilidad_c33',
       'categoría_a_riesgo_normal_bienes_dados_en_leasing_c34',
       'categoría_b_riesgo_aceptable_bienes_dados_en_leasing',
       'categoría_c_riesgo_apreciable_bienes_dados_en_leasing',
       'categoría_d_riesgo_significativo_bienes_dados_en_leasing',
       'categoría_e_riesgo_de_incobrabilidad_bienes_dados_en_leasing',
       'microcréditos,_otras_garantías', 'categoría_a_riesgo_normal_c40',
       'categoría_b_riesgo_aceptable_c41', 'categoría_c_riesgo_apreciable_c42',
       'categoría_d_riesgo_significativo_c43',
       'categoría_e_riesgo_de_incobrabilidad_c44',
       'categoría_a_riesgo_normal_bienes_dados_en_leasing_c45',
       'categoría_b_riesgo_aceptable_bienes_dados_en_leasin_c46',
       'categoría_c_riesgo_apreciable_bienes_dados_en_leasing_c47',
       'categoría_d_riesgo_significativo_bienes_dados_en_leasing_c48',
       'categoría_e_riesgo_de_incobrabilidad_bienes_dados_en_leasing_c49',
       'categoría_a_riesgo_normal,_garantía_idónea,_créditos_y_leasing_comerciales',
       'categoría_b_riesgo_aceptable,_garantía_idónea,_créditos_y_leasing_comerciales',
       'categoría_c_riesgo_apreciable,_garantía_idónea,_créditos_y_leasing_comerciales',
       'categoría_d_riesgo_significativo,_garantía_idónea,_créditos_y_leasing_comerciales',
       'categoría_e_riesgo_de_incobrabilidad,_garantía_idónea,_créditos_y_leasing_comerciales',
       'categoría_a_riesgo_normal,_otras_garantías,_créditos_y_leasing_comerciales',
       'categoría_b_riesgo_aceptable,_otras_garantías,_créditos_y_leasing_comerciales',
       'categoría_c_riesgo_apreciable,_otras_garantías,_créditos_y_leasing_comerciales',
       'categoría_d_riesgo_significativo,_otras_garantías,_créditos_y_leasing_comerciales',
       'categoría_e_riesgo_de_incobrabilidad,_otras_garantías,_créditos_y_leasing_comerciales',
       'provisión_créditos_de_vivienda',
       'provisión_créditos_y_operaciones_de_leasing_de_consumo',
       'provisión_microcréditos',
       'provisión_créditos_y_operaciones_de_leasing_comerciales',
       'provisión_general', 'número_de_cdt', 'número_de_cuentas_centralizadas',
       'número_de_oficinas', 'número_de_empleados_contratados',
       'número_de_empleados_subcontratados',
       'componente_contracíclico_provisión_individual',
       'derechos_de_transferencia_de_cartera_de_créditos_por_operaciones_de_apoyos_transitorios_de_liquidez',
       'préstamos_a_empleados', 'deterioro_(provisión)_préstamos_a_empleados',
       'crédito_de_consumo_de_bajo_monto'],
      dtype='str')

In [6]:
data_distribucion_cartera.columns

Index(['tipo_entidad', 'codigo_entidad', 'nombreentidad', 'fecha_corte',
       'unicap', 'descrip_uc', 'renglon', 'desc_renglon',
       '(1)_saldo_de_la_cartera_a_la_fecha_de_corte_del_reporte',
       '(2)_vigente', '(3)_vencida_1-2_meses', '(4)_vencida_2-3_meses',
       '(5)_vencida_1-3_meses', '(6)_vencida_3-4_meses',
       '(7)_vencida_>_de_4_meses', '(8)_vencida_3-6_meses',
       '(9)_vencida_+6_meses', '(10)_vencida_1-4_meses',
       '(11)_vencida_4-6_meses', '(12)_vencida_6-12_meses',
       '(13)_vencida_12-18_meses', '(14)_vencida_>_12_meses',
       '(15)_vencida_>_18_meses', '(16)_número_de_clientes_mora_>_30_días',
       '(17)_calificación_de_riesgo_a_/_número_de_clientes',
       '(18)_calificación_de_riesgo_a_/_saldo',
       '(19)_calificación_de_riesgo_b_/_número_de_clientes',
       '(20)_calificación_de_riesgo_b_/_saldo',
       '(21)_calificación_de_riesgo_c_/_número_de_clientes',
       '(22)_calificación_de_riesgo_c_/_saldo',
       '(23)_calificación_de_riesgo_d_/_número_de_clientes',
       '(24)_calificación_de_riesgo_d_/_saldo',
       '(25)_calificación_de_riesgo_e_/_número_de_clientes',
       '(26)_calificación_de_riesgo_e_/_saldo'],
      dtype='str')

In [7]:
#Limpieza de tildes
def limpiar_texto(texto):
    if isinstance(texto, str):
        texto = unicodedata.normalize('NFKD', texto)
        texto = ''.join([c for c in texto if not unicodedata.combining(c)])
    return texto

In [8]:
#Llamar función de limpieza
data_saldo_captaciones.columns = data_saldo_captaciones.columns.map(limpiar_texto)
data_distribucion_cartera.columns = data_distribucion_cartera.columns.map(limpiar_texto)

In [9]:
municipios = data_saldo_captaciones[["codigo_del_departamento",
                                     "codigo_del_municipio",
                                     "nombre_del_municipio"]]
municipios_unique = (
    municipios
    .drop_duplicates()
    .reset_index(drop=True))
municipios_unique

      codigo_del_departamento  codigo_del_municipio nombre_del_municipio
0                           8                   824               TOTORO
1                          15                   245             EL BANCO
2                           7                     1            FLORENCIA
3                          10                   419         LOS CORDOBAS
4                          22                     1            SINCELEJO
...                       ...                   ...                  ...
1149                       12                    73               BAGADO
1150                       12                   745                 SIPI
1151                       29                   460        MIRITI-PARANA
1152                       29                   536         PUERTO ARICA
1153                       12                   600            RIO QUITO

[1154 rows x 3 columns]

In [10]:
d_departamentos = municipios_unique[
    (municipios_unique["nombre_del_municipio"].str.startswith("TOTAL",na=False)) |
    (municipios_unique["nombre_del_municipio"].str.startswith("BOGOTA",na=False))].copy()

#Limpiar nombres
d_departamentos["nombre_del_municipio"] = (
    d_departamentos["nombre_del_municipio"]
    .str.replace("TOTAL ", "", regex=False)
    .str.lower() # Convert to lowercase for consistent replacement
    .str.replace("nari#o", "Nariño", regex=False) # Replace lowercase 'nari#o'
    .str.title()) # Apply title casing afterwards

#Renombrar columna
d_departamentos = d_departamentos.rename(
    columns={
    "nombre_del_municipio": "nombre_del_departamento"})

# Diccionario departamento -> región
regiones = {
    "Bogota": "Andina",
    "Antioquia": "Andina",
    "Magdalena": "Caribe",
    "Nariño": "Pacífica",
    "Choco": "Pacífica",
    "Cesar": "Caribe",
    "Santander": "Andina",
    "Cordoba": "Caribe",
    "Nacional": "Nacional",
    "Cauca": "Pacífica",
    "Valle Del Cauca": "Pacífica",
    "Caldas": "Andina",
    "Sucre": "Caribe",
    "N. Santander": "Andina",
    "Arauca": "Orinoquía",
    "Caqueta": "Amazonía",
    "Atlantico": "Caribe",
    "Guajira": "Caribe",
    "Boyaca": "Andina",
    "Risaralda": "Andina",
    "Bolivar": "Caribe",
    "Casanare": "Orinoquía",
    "Cundinamarca": "Andina",
    "Quindio": "Andina",
    "Tolima": "Andina",
    "Meta": "Orinoquía",
    "Huila": "Andina",
    "S. Andres Y Prov.": "Insular",
    "Vaupes": "Amazonía",
    "Amazonas": "Amazonía",
    "Guaviare": "Amazonía",
    "Vichada": "Orinoquía",
    "Putumayo": "Amazonía",
    "Guainia": "Amazonía"
}

# Agregar columna región
d_departamentos["region"] = (
    d_departamentos["nombre_del_departamento"]
    .map(regiones)
)

d_departamentos

,codigo_del_departamento,codigo_del_municipio,nombre_del_departamento,region
6,1,999,Antioquia,Andina
11,15,999,Magdalena,Caribe
15,17,999,Nariño,Pacífica
17,12,999,Choco,Pacífica
19,9,999,Cesar,Caribe
23,21,999,Santander,Andina
24,10,999,Cordoba,Caribe
26,34,5,Nacional,Nacional
29,3,1,Bogota,Andina
30,8,999,Cauca,Pacífica
32,24,999,Valle Del Cauca,Pacífica
36,6,999,Caldas,Andina
40,22,999,Sucre,Caribe
43,18,999,N. Santander,Andina
50,25,999,Arauca,Orinoquía
51,7,999,Caqueta,Amazonía
59,2,999,Atlantico,Caribe
77,14,999,Guajira,Caribe
79,5,999,Boyaca,Andina
80,20,999,Risaralda,Andina
82,4,999,Bolivar,Caribe
131,26,999,Casanare,Orinoquía
153,11,999,Cundinamarca,Andina
155,19,999,Quindio,Andina
164,23,999,Tolima,Andina
167,16,999,Meta,Orinoquía
180,13,999,Huila,Andina
230,28,999,S. Andres Y Prov.,Insular
295,32,999,Vaupes,Amazonía
336,29,999,Amazonas,Amazonía
444,31,999,Guaviare,Amazonía
463,33,999,Vichada,Orinoquía
556,27,999,Putumayo,Amazonía
614,30,999,Guainia,Amazonía

In [11]:
#Diccionario Departamentos y Regiones
dic_departamentos = d_departamentos.set_index(
    'codigo_del_departamento'
    )['nombre_del_departamento']

dic_regiones = d_departamentos.set_index(
    'codigo_del_departamento'
    )['region']

In [12]:
#Mapear el nombre del departamento
import pandas as pd

#Mapear el nombre del departamento
data_saldo_captaciones["nombre_del_departamento"] = (
    data_saldo_captaciones["codigo_del_departamento"]
    .map(dic_departamentos)
)

#Mover al lado de la columna codigo_del_departamento
columna = data_saldo_captaciones.pop("nombre_del_departamento")

posicion = (
    data_saldo_captaciones.columns
    .get_loc("codigo_del_departamento") + 1)

data_saldo_captaciones.insert(
    posicion,
    "nombre_del_departamento",
    columna)

# Mapear region
data_saldo_captaciones["region"] = (
    data_saldo_captaciones["codigo_del_departamento"]
    .map(dic_regiones)
)

#Mover al lado de la columna codigo_del_departamento
columna = data_saldo_captaciones.pop("region")

posicion = (
    data_saldo_captaciones.columns
    .get_loc("nombre_del_departamento") + 1)

data_saldo_captaciones.insert(
    posicion,
    "region",
    columna)

In [13]:
#Mapear Nombre de las Entidades
nombreentidad = data_distribucion_cartera[["tipo_entidad",
                                     "codigo_entidad",
                                     "nombreentidad"]]

d_entidades = (
    nombreentidad
    .drop_duplicates()
    .reset_index(drop=True))
d_entidades

,tipo_entidad,codigo_entidad,nombreentidad
0,1,12,Banco Gnb Sudameris
1,1,6,Itaú Banco Itaú.
2,1,9,Citibank
3,1,23,Banco De Occidente
4,1,57,Banco Pichincha S.A.
...,...,...,...
63,1,64,"Banco J.P. Morgan Colombia S.A., (La ""Sociedad"")"
64,1,66,"Banco Btg Pactual Colombia, Banco Btg Pactual ..."
65,2,47,Itaú Bba Colombia S.A.
66,2,11,"Corficolombiana S.A., Corficol S.A. O Corfi S.A."
67,2,42,"Bnp Paribas Colombia (La ""Sociedad"")"

In [14]:
#Diccionario Nombre de Entidades
dic_entidades = d_entidades.set_index(
    "codigo_entidad"
    )["nombreentidad"]

In [15]:
#Mapear el nombre de la entidad
data_saldo_captaciones["nombreentidad"] = (
    data_saldo_captaciones["codigo_de_entidad"]
    .map(dic_entidades.to_dict()))

#Mover al lado de la columna codigo_de_entidad
columna_entidad = data_saldo_captaciones.pop("nombreentidad")

posicion_entidad = (
    data_saldo_captaciones.columns
    .get_loc("codigo_de_entidad") + 1)

data_saldo_captaciones.insert(
    posicion_entidad,
    "nombreentidad",
    columna_entidad)

In [16]:
 #Filtrar filas donde nombre entidad NO sea NaN
data_saldo_captaciones = (
    data_saldo_captaciones[
        data_saldo_captaciones["nombreentidad"].notna()
    ].reset_index(drop=True))

data_saldo_captaciones

,tipo_de_entidad,codigo_de_entidad,nombreentidad,codigo_del_departamento,nombre_del_departamento,region,codigo_del_municipio,nombre_del_municipio,fecha_de_corte,depositos_en_cuenta_corriente_bancaria,...,numero_de_cdt,numero_de_cuentas_centralizadas,numero_de_oficinas,numero_de_empleados_contratados,numero_de_empleados_subcontratados,componente_contraciclico_provision_individual,derechos_de_transferencia_de_cartera_de_creditos_por_operaciones_de_apoyos_transitorios_de_liquidez,prestamos_a_empleados,deterioro_(provision)_prestamos_a_empleados,credito_de_consumo_de_bajo_monto
0,1,43,Banco Agrario De Colombia O Banagrario.,8,Cauca,Pacífica,824,TOTORO,2006-03-31,5.185171e+08,...,0.0,0,0,18131663.0,7542349.0,5.621906e+06,1244002.0,0.000000e+00,0.00,0.0
1,1,1,Cooperativa Financiera De Antioquia Cfa,15,Magdalena,Caribe,245,EL BANCO,2006-03-31,1.871890e+09,...,0.0,0,0,0.0,22760299.0,4.935148e+06,5401739.0,2.970775e+07,0.00,0.0
2,1,43,Banco Agrario De Colombia O Banagrario.,7,Caqueta,Amazonía,1,FLORENCIA,2006-03-31,3.038650e+09,...,0.0,0,0,73089887.0,16986009.0,5.653744e+07,99104495.0,0.000000e+00,0.00,0.0
3,1,43,Banco Agrario De Colombia O Banagrario.,10,Cordoba,Caribe,419,LOS CORDOBAS,2006-03-31,1.712118e+08,...,0.0,0,0,15036.0,25666.0,1.709273e+07,152063902.0,0.000000e+00,0.00,0.0
4,1,43,Banco Agrario De Colombia O Banagrario.,11,Cundinamarca,Andina,398,LA PEÑA,2006-03-31,2.711152e+08,...,0.0,0,0,7736708.0,4538826.0,5.529463e+06,1521614.0,0.000000e+00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289616,1,43,Banco Agrario De Colombia O Banagrario.,23,Tolima,Andina,585,PURIFICACION,2025-09-30,1.493830e+09,...,112.0,0,1,8.0,1.0,2.438864e+08,0.0,0.000000e+00,0.00,0.0
289617,1,7,Bancolombia,2,Atlantico,Caribe,638,SABANALARGA,2025-09-30,6.180318e+09,...,435.0,0,1,2.0,0.0,5.287958e+08,0.0,7.305873e+08,7664699.29,0.0
289618,1,43,Banco Agrario De Colombia O Banagrario.,23,Tolima,Andina,555,PLANADAS,2025-09-30,2.562557e+10,...,122.0,0,1,9.0,0.0,1.295540e+08,0.0,0.000000e+00,0.00,0.0
289619,1,43,Banco Agrario De Colombia O Banagrario.,5,Boyaca,Andina,542,PESCA,2025-09-30,4.564936e+08,...,232.0,0,1,5.0,0.0,2.591351e+07,0.0,0.000000e+00,0.00,0.0
289620,4,128,Nu O Nu Financiera,15,Magdalena,Caribe,703,SAN ZENON,2025-09-30,0.000000e+00,...,0.0,0,0,0.0,0.0,7.087672e+04,0.0,0.000000e+00,0.00,0.0

In [17]:
data_saldo_captaciones.rename(columns={"nombreentidad": "nombre_entidad"}, inplace=True)
data_distribucion_cartera.rename(columns={"nombreentidad": "nombre_entidad"}, inplace=True)

In [ ]:
data_distribucion_cartera.info()

In [20]:
data_saldo_captaciones.to_csv(f"{ruta_base}\Bases_datos\saldo_captaciones_limpio.csv", 
                              index=False, 
                              encoding="utf-8-sig",
                              sep="|"
                              )

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_24164\1165854248.py:1: SyntaxWarning: invalid escape sequence '\B'
  data_saldo_captaciones.to_csv(f"{ruta_base}\Bases_datos\saldo_captaciones_limpio.csv",